# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcThetaXY <- function(Gamma, diagThetaYY) {
    .Call('spacemap_calcThetaXY', PACKAGE = 'spacemap', Gamma, diagThetaYY)
}

calcThetaYY <- function(ParCor, diagThetaYY) {
    .Call('spacemap_calcThetaYY', PACKAGE = 'spacemap', ParCor, diagThetaYY)
}

conc2parcor <- function(D) {
    .Call('spacemap_conc2parcor', PACKAGE = 'spacemap', D)
}

nonZeroWhole <- function(Gamma, tol) {
    .Call('spacemap_nonZeroWhole', PACKAGE = 'spacemap', Gamma, tol)
}

nonZeroUpper <- function(ParCor, tol) {
    .Call('spacemap_nonZeroUpper', PACKAGE = 'spacemap', ParCor, tol)
}

gaussCondLogLik <- function(Y, X, ThetaYY, ThetaXY) {
    .Call('spacemap_gaussCondLogLik', PACKAGE = 'spacemap', Y, X, ThetaYY, ThetaXY)
}

gaussLogLik <- function(Theta, Y) {
    .Call('spacemap_gaussLogLik', PACKAGE = 'spacemap', Theta, Y)
}

olsRefitSpacemap <- function(Y, X, ParCor, Gamma, sigma, RSS, tol, ridge = 0.1) {
    .Call('spacemap_olsRefitSpacemap', PACKAGE = 'spacemap', Y, X, ParCor, Gamma, sigma, RSS, tol, ridge)
}

olsRefitSpace <- function(Y, ParCor, sigma, RSS, tol, ridge = 0.1) {
    .Call('spacemap_olsRefitSpace', PACKAGE = 'spacemap', Y, ParCor, sigma, RSS, tol, ridge)
}

doRemMap <- function(Ym, Xm, Wm, rlasso, rgroup, tol, maxIter) {
    .Call('spacemap_doRemMap', PACKAGE = 'spacemap', Ym, Xm, Wm, rlasso, rgroup, tol, maxIter)
}

doSpace <- function(Ym, sigma_sr, lasso, ridge, tol, maxIter, beta_init, init) {
    .Call('spacemap_doSpace', PACKAGE = 'spacemap', Ym, sigma_sr, lasso, ridge, tol, maxIter, beta_init, init)
}

doSpaceMap <- function(Ym, Xm, Wm, sigma_sr, slasso, sridge, rlasso, rgroup, tol, maxIter, beta_init, init) {
    .Call('spacemap_doSpaceMap', PACKAGE = 'spacemap', Ym, Xm, Wm, sigma_sr, slasso, sridge, rlasso, rgroup, tol, maxIter, beta_init, init)
}

